# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/asness_will/Desktop/Everything_Academic/research/numerical_pdes/stokes-to-2560

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/asness_will/Desktop/Everything_Academic/research/numerical_pdes/stokes-to-2560

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/asness_will/Desktop/Everything_Academic/research/numerical_pdes/stokes-to-2560/CMakeFiles /Users/asness_will/Desktop/Everything_Academic/research/numerical_pdes/stokes-to-2560//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/asness_will/Desktop/Everything_Academic/research/numerical_pdes/stokes-to-2560/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stokes

# Build rule for target.
stokes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stokes
.PHONY : stokes

# fast build rule for target.
stokes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stokes.dir/build.make CMakeFiles/stokes.dir/build
.PHONY : stokes/fast

#=============================================================================
# Target rules for targets named stokes_with_density

# Build rule for target.
stokes_with_density: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stokes_with_density
.PHONY : stokes_with_density

# fast build rule for target.
stokes_with_density/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stokes_with_density.dir/build.make CMakeFiles/stokes_with_density.dir/build
.PHONY : stokes_with_density/fast

#=============================================================================
# Target rules for targets named stokes_to

# Build rule for target.
stokes_to: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stokes_to
.PHONY : stokes_to

# fast build rule for target.
stokes_to/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stokes_to.dir/build.make CMakeFiles/stokes_to.dir/build
.PHONY : stokes_to/fast

#=============================================================================
# Target rules for targets named dataclean

# Build rule for target.
dataclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dataclean
.PHONY : dataclean

# fast build rule for target.
dataclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dataclean.dir/build.make CMakeFiles/dataclean.dir/build
.PHONY : dataclean/fast

stokes.o: stokes.cpp.o
.PHONY : stokes.o

# target to build an object file
stokes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stokes.dir/build.make CMakeFiles/stokes.dir/stokes.cpp.o
.PHONY : stokes.cpp.o

stokes.i: stokes.cpp.i
.PHONY : stokes.i

# target to preprocess a source file
stokes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stokes.dir/build.make CMakeFiles/stokes.dir/stokes.cpp.i
.PHONY : stokes.cpp.i

stokes.s: stokes.cpp.s
.PHONY : stokes.s

# target to generate assembly for a file
stokes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stokes.dir/build.make CMakeFiles/stokes.dir/stokes.cpp.s
.PHONY : stokes.cpp.s

stokes_to.o: stokes_to.cpp.o
.PHONY : stokes_to.o

# target to build an object file
stokes_to.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stokes_to.dir/build.make CMakeFiles/stokes_to.dir/stokes_to.cpp.o
.PHONY : stokes_to.cpp.o

stokes_to.i: stokes_to.cpp.i
.PHONY : stokes_to.i

# target to preprocess a source file
stokes_to.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stokes_to.dir/build.make CMakeFiles/stokes_to.dir/stokes_to.cpp.i
.PHONY : stokes_to.cpp.i

stokes_to.s: stokes_to.cpp.s
.PHONY : stokes_to.s

# target to generate assembly for a file
stokes_to.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stokes_to.dir/build.make CMakeFiles/stokes_to.dir/stokes_to.cpp.s
.PHONY : stokes_to.cpp.s

stokes_with_density.o: stokes_with_density.cpp.o
.PHONY : stokes_with_density.o

# target to build an object file
stokes_with_density.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stokes_with_density.dir/build.make CMakeFiles/stokes_with_density.dir/stokes_with_density.cpp.o
.PHONY : stokes_with_density.cpp.o

stokes_with_density.i: stokes_with_density.cpp.i
.PHONY : stokes_with_density.i

# target to preprocess a source file
stokes_with_density.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stokes_with_density.dir/build.make CMakeFiles/stokes_with_density.dir/stokes_with_density.cpp.i
.PHONY : stokes_with_density.cpp.i

stokes_with_density.s: stokes_with_density.cpp.s
.PHONY : stokes_with_density.s

# target to generate assembly for a file
stokes_with_density.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stokes_with_density.dir/build.make CMakeFiles/stokes_with_density.dir/stokes_with_density.cpp.s
.PHONY : stokes_with_density.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dataclean"
	@echo "... stokes"
	@echo "... stokes_to"
	@echo "... stokes_with_density"
	@echo "... stokes.o"
	@echo "... stokes.i"
	@echo "... stokes.s"
	@echo "... stokes_to.o"
	@echo "... stokes_to.i"
	@echo "... stokes_to.s"
	@echo "... stokes_with_density.o"
	@echo "... stokes_with_density.i"
	@echo "... stokes_with_density.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

